version: "3.7"

services:
  kaillera_server:
    image: maven:3.8-jdk-11
    command: sh -c "mvn -f /home/app/emulinker/pom.xml compile exec:java"
    working_dir: /emulinker
    ports:
      - 27888-27999:27888-27999/udp
    volumes:
      - ./:/home/app/

  graphite:
    profiles: ["debug"]
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    deploy:
      restart_policy:
        condition: any
